template: template\reitai12.html
output: reitai12.html
base: yaml
input: [auto.yml,nplusplus.yml,felishia.yml]

double:
- auto:
    nplusplus: autoplus
    felishia: autofeli
- nplusplus:
    auto: autoplus
    felishia: aplusplus
- felishia:
    auto: autofeli
    nplusplus: aplusplus
- aplusplus:
    auto: trio
- autofeli:
    nplusplus: trio
- autoplus:
    felishia: trio
